<a href="https://colab.research.google.com/github/saigowtham627/Fundementals/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Numpy is the fundemental package for scientific computing using Python*

*It is a python library that provides multi dimensional array object, various derived objects(Such as masked arrays and matrices), and an assortment of routines for fast operation on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete fourier transforms, basic linear algebra, basic statical operations, random simulation and much more*

*When coming to processing GB's of data, WKT python is slower than C lang. The data types of Python like List and Array are slow, So people has built Numpy library in C language and Python acts as a wrapper around it. This way Numpy is fast*


**Numpy Arrays vs Python Sequences(Arrays, List)**

*Numpy array have a fixed size creation, unlike Python lists(which can grow dynamically). Changing the size of the ndarray will create a new array and delete the original one*

*Lists can store multiple data types, where as Numpy array can only store elements of same data type, and thus will be same size in Memory*

*Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficinetly and with less code than is possible using Python's built in sequence*



In [ ]:
import numpy as np
#numpy arrays can be created using function called np.array
a = np.array([1,2,3]) #np.array function needs a list to be provided
print(a)

#To know the type of array we use "type"
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#For creating a 2-D numpy array, we have to pass a 2-D list
b = np.array([[1, 2, 3],
          [4, 5, 7]]) #Both the lists must be of same type

print(b)

print(type(b))

[[1 2 3]
 [4 5 7]]
<class 'numpy.ndarray'>


In [ ]:
#Creating a 3-d array with dimensions 1x3x3, which is 1 block, 3 rows and 3 columns
c = np.array([[[1, 2, 3],
           [4, 5, 6],
           [9, 8, 7]]])

print(c)

print(type(c))

[[[1 2 3]
  [4 5 6]
  [9 8 7]]]
<class 'numpy.ndarray'>


In [ ]:
#Creating an numpy array with dimension of 2x2x3
d = np.array([[[1, 2, 3], [4, 5, 6]], #Block 1
          [[7, 8, 9], [10, 11, 12]]])

#Numbers of list will be always enclosed in Yellow Braces
#The first [] (Purple colour) is denotes the start and end,
#The second [](Blue colour) is the Block Differentiator
#The third [](Yellow colour) is the list
print(d)
print(type(d))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [ ]:
#Create a numpy array with dimensions 3x3x3.
#3 blocks, 3 rows and 3 columns

e = np.array([[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[10, 11, 12],
           [13, 14, 15],
           [16, 17, 18]],

          [[91, 92, 93],
           [94, 95, 96],
           [80, 81, 82]]])

print(e)
print(type(e))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[91 92 93]
  [94 95 96]
  [80 81 82]]]
<class 'numpy.ndarray'>


In [ ]:
#dtype, we can also pass the data type of the array.
np.array([1.90, 2, 3], dtype = float) #Treats the floating point number as integer

array([1.9, 2. , 3. ])

In [ ]:
#ARANGE not arrange
f = np.arange(0, 10, 2) #0 is the start, 10 is end and 2 is the difference. End will not be counted in the list

print(f)

[0 2 4 6 8]


In [ ]:
#Reshape, function turns a given numpy array into a desired shape
np.arange(12).reshape(3,4) #No.of rows x No.of columns arguments passed to reshape must be equal to number of elements in the array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.arange(12).reshape(2,3) #Throws an error because the number of elements are 12 and we can't fit them into 2 rows and 3 columns


ValueError: cannot reshape array of size 12 into shape (2,3)

In [ ]:
#np.ones, Used to create numpy arrays with all ones in it.
"""WE HAVE TO PROVIDE SHAPE OF THE ARRAY IN THE FORM OF A TUPLE"""

np.ones((3,4), dtype=int)

"""These are useful to initialize the weight matrix"""

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#By using np.zeros we can initialize with zeros
np.zeros((3,4), dtype = float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Same like Zeros and Ones, we can also initialize with np.random
h = np.random.rand(3,4)
print(h)
"""Unlike in Zeros and Ones, we dont need to pass the dimension as tuple when we are using rand function"""

[[0.58771677 0.70157962 0.39590986 0.9207092 ]
 [0.80178339 0.5940395  0.57616664 0.04915651]
 [0.42423334 0.83927229 0.23689626 0.55320937]]


'Unlike in Zeros and Ones, we dont need to pass the dimension as tuple when we are using rand function'

In [ ]:
g = np.random.random((3,4)) #Random is a class in which random is the method
print(g)
"""But when we are using random.random we have to pass the tuple itself"""

[[0.72664699 0.69295033 0.30030998 0.21082705]
 [0.543575   0.13802339 0.06346965 0.28742048]
 [0.80857367 0.74101044 0.30374264 0.18976624]]


'But when we are using random.random we have to pass the tuple itself'

In [ ]:
"""LinSpace is used to generate points from equal distances, Basically the difference every 2 consecutive points will be the Same"""

np.linspace(-10, 10) #Here we didn't specify the number of points to be generated so by defaultly it generates 50 points

np.linspace(-10, 10, 5) #Gives 5 equally spaced points from -10 to 10

array([-10.,  -5.,   0.,   5.,  10.])

In [ ]:
#np.identity is used to create Identity matrix.
np.identity(10)  #Since Identity matrix is a square matrix only one argument is sufficient.

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#Array Attributes

In [ ]:
a1 = np.arange(10) #Vector
a2 = np.arange(12, dtype = int).reshape(3,4) #Matrix
a3 = np.arange(8).reshape(2,2,2) #Tensor

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
"""ndim is used to know the dimension of the array, but not the shape"""

a1.ndim #Gives 1, since vector proceeds in 1 direction only
a2.ndim #Gives 2, since matrix has 2 dimensions rows and columns
a3.ndim #Gives 3, since tensor has 3 dimensions, they are Blocks, Rows and Columns

3

In [ ]:
#Shape, is used to know the shape of the array
a1.shape #Remember that shape is not a method, where as reshape is a method
a2.shape
a3.shape

(2, 2, 2)

In [ ]:
#Size , gives the number of items in the array
a1.size
a2.size
a3.size

8

In [ ]:
"""In Colab we have 2 types of integers, int32 and int64, by default the integers will be of type int64 and size of each integer 64 will be 8 bytes"""

a1.itemsize #Gives the size of each item/element in the array

8

In [ ]:
a1.dtype #Gives the data type of the array

dtype('int64')

#Changing data types

In [ ]:
#astype is used to change the datatype of the column
a3.astype(np.int64) #Changes the datatype of the array to int64

"""By transforming the data into lower data types we can save memory"""

'By transforming the data into lower data types we can save memory'

#Array Operations

In [ ]:
#Uisng Numpy we can perform any type of mathematical opearation
a1 = np.arange(12).reshape(3,4) #Generates 12(3*4) numbers in range of 0(inclusive) to 12(exclusive) and places them in 3x4 matrix
a2 = np.arange(12,24).reshape(3,4) #Generates 12 numbers in range of 12(inclusive) to 24(exclusive) and places them in a 3x4 matrix

print(a1)
print("xxxxxxxxxx")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
xxxxxxxxxx
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


*We can perform both scalar and vector operations on arrays*

*Scalar operations include Arthematical and Relational*

In [ ]:
print(a1 + 100) #Adds 100 to every element of the array.
print("--------------------------")
print(a1 - 1) #Subtracts 1 from every element of the array.
print("--------------------------")
print(a1 * 100) #Multiplies each element of array with 100
print("--------------------------")
print(a1 / 50) #Divides each element of the array with 50
print("--------------------------")
print(a1 // 3) #Performs floor division with each element in the array
print("--------------------------")
print(a1 % 5) #Performs modulo operation with each element in the array

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]
--------------------------
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
--------------------------
[[   0  100  200  300]
 [ 400  500  600  700]
 [ 800  900 1000 1100]]
--------------------------
[[0.   0.02 0.04 0.06]
 [0.08 0.1  0.12 0.14]
 [0.16 0.18 0.2  0.22]]
--------------------------
[[0 0 0 1]
 [1 1 2 2]
 [2 3 3 3]]
--------------------------
[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


In [ ]:
#Relational
a1 < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [ ]:
"""Vector Operations""" """Operations between 2 vectors"""
#Arthematic

a1 + a2
a1 - a2
a1 * a2
a1 / a2
a2 // a1
a2 % a1
a1 ** a2

<ipython-input-64-31a5e6df1805>:8: RuntimeWarning: divide by zero encountered in floor_divide
  a2 // a1
<ipython-input-64-31a5e6df1805>:9: RuntimeWarning: divide by zero encountered in remainder
  a2 % a1


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
b1 = np.random.rand(3,4) #Produces random numbers between 0 and 1 in a 3x4 matrix
b1 = np.round(b1 * 100)
b1

array([[96., 41., 91., 29.],
       [65.,  1., 28., 44.],
       [47., 22., 59., 98.]])

In [ ]:
#Maximum of array
np.max(b1)

98.0

In [ ]:
#Minimum of array
np.min(b1)

1.0

In [ ]:
"""Sum of elments in the array"""
np.sum(b1)

621.0

In [ ]:
np.product(b1)

4.972985243558492e+18

In [ ]:
"""Axis = 0 means we are referring to a Column"""
"""Axis = 1 means we are referring to a Row (Remember like ROWAN)"""

np.max(b1, axis = 1) #Returns maximum of each row
np.min(b1, axis = 1) #Returns minimum of each row

np.min(b1, axis = 0) #Returns minimum of each column
np.max(b1, axis = 0) #Returns maximum of each column

array([96., 41., 91., 98.])

In [ ]:
#Log and Exp functions
np.log(a1)

np.exp(a1)  #e power each element of the array

<ipython-input-129-409141012ea4>:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
np.sum(b1, axis=1) #Returns the sum of elements of each row
np.sum(b1, axis=0) #Returns the sum of elements of each column

np.prod(b1, axis=1) #Returns product of elements of each row
np.prod(b1, axis=0) #Returns the product of elements of each column

array([293280.,    902., 150332., 125048.])

In [ ]:
"""Statistical functions"""

np.mean(b1) #Mean of all elements of the array
np.mean(b1, axis=0) #Mean of elements of each column of the array
np.mean(b1, axis=1) #Mean of elements of each row of the array

np.median(b1) #Median of all elements of the array
np.median(b1, axis=0) #Median of all elements of each column of the array
np.median(b1, axis=1) #Median of all elements of each row of the array

"""3*median = 2*mean + mode"""
np.std(b1) #Standard deviation of all the elements of the array
np.std(b1, axis=0)
np.std(b1, axis=1)

np.var(b1) #Variance is referred as Var but not variance
np.var(b1, axis=1) #Varinace of elements of each row in the array
np.var(b1, axis=0) #variance of elements of each column in the array


array([876.6875, 546.25  , 752.25  ])

In [ ]:
#Trignometric Functions
np.sin(b1) * np.cos(b1) * np.tan(b1)

array([[9.67444853e-01, 2.51611511e-02, 1.12333526e-02, 4.40409932e-01],
       [6.83645665e-01, 7.08073418e-01, 7.33899461e-02, 3.13358152e-04],
       [1.52703167e-02, 7.83456762e-05, 4.05435290e-01, 3.28766771e-01]])

In [ ]:
"""Dot product""" #Most useful
#Let (a, b) and (c,d) are the dimensions of the arrays to be performed dot product .
#Dot product can only be performed only of b==c i.e; No of rows of one array is equal to no of columns of another column.
d1 = np.arange(24).reshape(4,6)
d2 = np.arange(24).reshape(6,4)

np.dot(d1,d2) #4x4 matrix is expected


array([[ 220,  235,  250,  265],
       [ 580,  631,  682,  733],
       [ 940, 1027, 1114, 1201],
       [1300, 1423, 1546, 1669]])

In [ ]:
#Round, Floor and Ceil
np.round(np.random.rand(3,4) * 3)

np.floor(np.random.rand(3,4) * 3)

np.ceil(np.random.rand(3,4) * 3)


array([[3., 2., 3., 1.],
       [2., 3., 3., 1.],
       [2., 2., 3., 3.]])

#Index and Slicing

In [ ]:
t1 = np.arange(10)
t2 = np.arange(16).reshape(4,4)
t3 = np.arange(27).reshape(3,3,3)

In [ ]:
t1[9] #Fetches the element at 9th index

9

In [ ]:
t2[2,2] #Fetches the element whose position is [2,2]

10

In [ ]:
t3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#Fetch the value of 17
t3[1,2,2] #As indexing in Python starts from zero. 1 corresponds to 2nd block, 2 corresponds to 3rd row and other 2 corresponds to 3rd column

17

In [ ]:
# Indexing helps us to fetch one element at a time, but slicing enables us to
# fetch multiple/Series of elements at a time

t1[5:8:2]

array([5, 7])

In [ ]:
t2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#Fetch 1row from t2
t2[0,:] #0 corresponds to 1st row and : corresponds to all columns

#Fetch 2 row from t2
t2[1,:]

#Fetch 15.
#15 is located at 3x3
t2[2,2]

#Fetch all the elements from 3rd column
t2[:,2] #3rd column from all rows

array([14])

In [ ]:
#Fetch 5, 6, 9 and 10 from t2
#We need 1 and 2 rows and 1 and 2 columns
t2[1:3,1:3] #3 will not be counted 1 and 2 are the only values taken

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
#Need all the elements placed at corners which are 0, 3, 12 and 15
t2[::3,::3] #We need 0 and 3rd row and 0 and 3rd column

#We need all the rows but with a jump of 3
#We need all columns but with a jump of 3

array([[ 0,  3],
       [12, 15]])

In [ ]:
#Fetch 1, 3, 9 and 11
t2[0::2,1::2] #0th row and 2nd row and 1st column and 3rd column

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
#Need 4 and 7
#Need only 1 st row, but 0 and 3rd column
t2[1,::3] #Equivalent to t2[1,0::3] i.e; Starting from 0th column we need 3rd column

array([4, 7])

In [ ]:
#Fetch 1,2,3,5,6 and 7
#Need 0th row and 1st row
#Need 1, 2 and 3 columns
t2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
t3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#t3 consists of 3 2d arrays.
#Fetch the 2nd 2-D array
t3[1] #Passing the index of the 2nd block

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
#Fetch 1st and 3rd block
t3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#Fetch 1st row in 1st block
#First go to that block and fetch the required elements
t3[0,1,:]

array([3, 4, 5])

In [ ]:
#Fetch middle column of the 2nd numpy array
t3[1,:,1]

array([10, 13, 16])

In [ ]:
#Return 22,23,25 and 26 from 3rd block
t3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
#Fetch 0,2,18 and 20
t3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

#Iterating through Arrays

In [ ]:
num = [100,99,98,95,100,90,49]

for i in num:
  print(i) #Prints the numbers but not the indices

100
99
98
95
100
90
49


In [ ]:
t1
for i in t1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#When we iterate over a loop of a 2-D array, everytime a row(1-D) gets printed

t2

for i in t2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [ ]:
t3
for i in t3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#For printing each item in the array
for i in np.nditer(t2):
  print(i)

#nditer converts any array of arbitary size into 1-D array and iterates through it
#here t2 is 2-d array, nditer converted it into 1-D array and iterated through it


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [ ]:
for i in np.nditer(t3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [ ]:
np.reshape(t2,(2,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
np.transpose(t3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
t3.T #Shorthand for transpose operation

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
#Ravel, converts array of any size into 1-D array
t3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
for i in t3.ravel():
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Stacking

In [ ]:
p1 = np.arange(12).reshape(4,3)
p2 = np.arange(12,24).reshape(4,3)

print(p1)
print(p2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
"""We have to pass the input as a tuple"""
np.hstack((p1,p2)) #Horizontal stacking, side by side

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17],
       [ 6,  7,  8, 18, 19, 20],
       [ 9, 10, 11, 21, 22, 23]])

In [ ]:
np.vstack((p1,p2)) #One on One stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

**For stacking, the shape must be the same**

#Splitting(Opposite of stacking)

In [ ]:
t2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(t2,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(t2,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]