<a href="https://colab.research.google.com/github/saigowtham627/Fundementals/blob/main/Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#np.sort
#Python sort gives the sorted array in the form of Python list
#np.sort gives numpy array in the sorted form

a = np.arange(1,100,25) #Produces numbers between 1 to 100 with a difference of 25
a

array([ 1, 26, 51, 76])

In [ ]:
a = np.random.randint(1,100,25)
a
np.sort(a) #Defaultly sorts in ASCENDING order, from small maginitude to larger magnitude

array([ 1,  2,  5,  6,  7, 12, 12, 16, 18, 24, 28, 31, 32, 32, 42, 43, 55,
       55, 59, 72, 75, 83, 91, 93, 97])

In [114]:
b = np.random.randint(200,300,25).reshape(5,5)
b

array([[272, 253, 264, 202, 209],
       [226, 265, 212, 294, 221],
       [298, 237, 299, 226, 229],
       [256, 270, 291, 227, 255],
       [260, 255, 210, 253, 222]])

In [ ]:
np.sort(b) #Default is row wise sorting, Performs sorting on each row

array([[216, 222, 262, 277, 293],
       [220, 223, 232, 283, 295],
       [248, 268, 271, 281, 287],
       [212, 222, 251, 271, 295],
       [234, 251, 269, 279, 299]])

In [ ]:
np.sort(b, axis=0) #Performs sorting on each column

array([[234, 222, 212, 222, 251],
       [248, 223, 216, 232, 271],
       [262, 251, 220, 268, 271],
       [295, 269, 279, 277, 283],
       [295, 281, 287, 299, 293]])

In [ ]:
#If we want to sort in descending order, i.e; From Larger magnitude to Smaller magnitude
np.sort(a)[::-1] #[::-1] is used to reverse the array which is sorted in ascending order, which gives us the descending order


array([97, 93, 91, 83, 75, 72, 59, 55, 55, 43, 42, 32, 32, 31, 28, 24, 18,
       16, 12, 12,  7,  6,  5,  2,  1])

In [ ]:
#np.append
#Similar to append in Python, appends the elements at the end of the array
a

array([ 2, 31,  6, 12, 32, 83, 72, 24, 12,  7, 55, 18, 42, 93, 16,  1, 43,
        5, 75, 59, 55, 97, 28, 91, 32])

In [ ]:
np.append(a,200) #We have to pass the name of the list and the number we want to append

array([  2,  31,   6,  12,  32,  83,  72,  24,  12,   7,  55,  18,  42,
        93,  16,   1,  43,   5,  75,  59,  55,  97,  28,  91,  32, 200])

In [ ]:
b

array([[262, 222, 216, 277, 293],
       [295, 223, 220, 232, 283],
       [248, 281, 287, 268, 271],
       [295, 251, 212, 222, 271],
       [234, 269, 279, 299, 251]])

In [ ]:
b.shape #Gives the shape of array
b.shape[0] #Gives the first element of shape of the array, which is basically number of Rows
b.shape[1] #Gives second element of shape of the array, which is number of columns

5

In [ ]:
#Append a column of 1's at the end of b
c = np.ones(5,dtype=np.int32).reshape(5,1)
c

array([[1],
       [1],
       [1],
       [1],
       [1]], dtype=int32)

In [ ]:
np.append(b,c,axis=1)

array([[262, 222, 216, 277, 293,   1],
       [295, 223, 220, 232, 283,   1],
       [248, 281, 287, 268, 271,   1],
       [295, 251, 212, 222, 271,   1],
       [234, 269, 279, 299, 251,   1]])

In [ ]:
b

array([[262, 222, 216, 277, 293],
       [295, 223, 220, 232, 283],
       [248, 281, 287, 268, 271],
       [295, 251, 212, 222, 271],
       [234, 269, 279, 299, 251]])

In [ ]:
#We can perform the above operation directly also
np.append(b, np.ones((b.shape[0],1)), axis = 1)

array([[262., 222., 216., 277., 293.,   1.],
       [295., 223., 220., 232., 283.,   1.],
       [248., 281., 287., 268., 271.,   1.],
       [295., 251., 212., 222., 271.,   1.],
       [234., 269., 279., 299., 251.,   1.]])

In [ ]:
#np.concatenate
#numpy.concatenate() function concatenates a sequence of arrays along existing axis
#Mostly used in Tabular data

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

#Concatenate is a replacement for stacking
"""While using Concatenate we have to pass the arrays in a tuple"""

np.concatenate((c,d), axis = 1) #Row wise concatenation
#We combine 2 rows, by taking each row from one matrix and joining with other row in other matrix

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=0)

#We join each columns

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
#np.unique
#np.unique() method gives us the unique values from an array given as parameter in np.unique method

e = [1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,4]
np.unique(e)

array([1, 2, 3, 4])

In [59]:
#expand_dims
#Used to make row vector or column vector in linear algebra
#It is used to pass the data in batches but not as Single value.

a.shape #(25,)
a = np.expand_dims(a, axis=1)
a.shape #(25,1)


(25, 1)

In [67]:
k = np.arange(10,30,5)
print(k)
k = np.expand_dims(k, axis=1)
k

[10 15 20 25]


array([[10],
       [15],
       [20],
       [25]])

In [85]:
x = np.random.randint(1,100,25)
x

array([24, 62, 85, 79, 47,  9, 54, 39, 30,  3,  9, 42, 40, 82, 85, 29, 97,
       79, 87, 35, 19, 89, 87, 94, 38])

In [76]:
#np.where
#np.where() function returns the """INDICES""" of the elements in an input array, where the condition passed is satisfied

np.where(x>50)


(array([ 2,  3,  5,  6, 10, 11, 16, 19, 22, 24]),)

In [89]:
#Replace all values>50 in x with 0
#np.where syntax - np.where(condition,If true replace with,If false what to do)

np.where(x>50,0,x) #If the number at index x is greater then 50, Replace it with 0
#Else keep it as it is like x


array([24,  0,  0,  0, 47,  9,  0, 39, 30,  3,  9, 42, 40,  0,  0, 29,  0,
        0,  0, 35, 19,  0,  0,  0, 38])

In [92]:
#Replace all even numbers with 0 and odd numbers with -1
np.where(x%2==0,0,-1)

array([ 0,  0, -1, -1, -1, -1,  0, -1,  0, -1, -1,  0,  0,  0, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  0,  0])

In [101]:
#np.argmax() returns/gives the "INDEX" of the largest element in the array
np.argmax(b, axis=1) #returns the indices of the max element in each row
np.argmax(b, axis=0) #returns the indices of the max element in each column
np.argmax(b) #Index of the largest element in the whole matrix

23

In [103]:
#np.argmin() , Opposite of argmax(), gives the "Index" of the minimum element
np.argmin(b,axis=0)
np.argmin(b,axis=1)

array([4, 0, 3, 3, 4])

In [118]:
z = np.random.randint(1,10,10).reshape(2,5) #random.randint can produce duplicate/repeated values also
z

array([[1, 5, 2, 7, 1],
       [1, 3, 1, 3, 5]])

In [120]:
#np.cumsum
#np.cumsum() is used to when we want to compute the cumulative sum of the elements over a given axis
np.cumsum(z, axis=0) #Last element of the each column is updated with Cumulative sum of all the elements of the column
np.cumsum(z, axis=1) #Last elment of the each row is updated with cuulative sum of all the elements of the row


array([[ 1,  6,  8, 15, 16],
       [ 1,  4,  5,  8, 13]])

In [122]:
#CumProd is similar to cumSum, it gives the prod of elements
np.cumprod(z, axis=0) #Prod along column, result is replaced with last element
np.cumprod(z, axis=1) #Prod along rows, result is replaced with last element


array([[ 1,  5, 10, 70, 70],
       [ 1,  3,  3,  9, 45]])

In [124]:
#np.percentile
#np.percentile() function is used to compute the nth percenile of the given data(array elements) along the specified axis.
#99Percentile means you are ahead of 99% of the people

p = np.random.randint(1,1000,250)
p

array([125, 991, 990, 900, 480, 835, 685, 722, 985,  31, 842, 721, 626,
       690, 173, 945,  59,  21, 271, 148, 832, 323, 837, 917, 940, 851,
       951, 784, 320, 483, 710, 412, 658, 183, 987, 231, 375, 408, 564,
       387, 297, 912,  19, 174, 702, 153, 741, 252, 143, 592, 502, 895,
       129, 584, 791, 639,  22,  22, 138, 307, 377, 147, 972, 509, 546,
       526, 329, 624,  85, 506, 485, 434, 538, 289, 943, 954, 131, 826,
        35, 991, 961, 990, 902, 304,  34, 817, 460, 499, 512,  15, 797,
       904, 394, 604,  29, 441, 498, 819, 656, 217, 213, 894, 258, 959,
       741, 498, 195, 945,  17, 406, 331, 345, 846, 965, 403, 549, 457,
       486, 345, 237, 917, 263, 142, 430, 816, 281, 328, 347, 501, 939,
       241, 395, 961, 264, 597, 860, 669, 476, 252, 668, 860, 693, 938,
       698, 525, 644, 138, 635,  88, 573, 719, 552, 728, 145, 621, 663,
       321, 917, 941, 546, 833, 323,  95, 121, 589, 839, 842,  91, 580,
        95, 234, 686, 310, 110, 907, 593, 855, 392,  90, 146, 22

In [132]:
np.percentile(p,100) #100 Percentile means-The highest number, 100% of the people are behind him
np.percentile(p,0) #0 Percentile means - 100% of the mmebers are greater than the number we are looking for and So it will be the minimum
np.percentile(p,50) #50 Percentile means, 50% of numbers are greater than the number and 50% of the numbers are less than the number. So it will be the median
#When the median is calculated, it first aranges the numbers in ascending order and returns the middle number

np.percentile(p,90)

"""Produes 937.1, It may not be in the array, its just the
measure that 90% of the numbers are less than 937.1 and 10% of the numbers are
greater than 937.1"""


'Produes 937.1, It may not be in the array, its just the \nmeasure that 90% of the numbers are less than 937.1 and 10% of the numbers are \ngreater than 937.1'

In [133]:
#np.histogram
#np.histogram() function represents the frequency of data distribution in the graphical form

p

array([125, 991, 990, 900, 480, 835, 685, 722, 985,  31, 842, 721, 626,
       690, 173, 945,  59,  21, 271, 148, 832, 323, 837, 917, 940, 851,
       951, 784, 320, 483, 710, 412, 658, 183, 987, 231, 375, 408, 564,
       387, 297, 912,  19, 174, 702, 153, 741, 252, 143, 592, 502, 895,
       129, 584, 791, 639,  22,  22, 138, 307, 377, 147, 972, 509, 546,
       526, 329, 624,  85, 506, 485, 434, 538, 289, 943, 954, 131, 826,
        35, 991, 961, 990, 902, 304,  34, 817, 460, 499, 512,  15, 797,
       904, 394, 604,  29, 441, 498, 819, 656, 217, 213, 894, 258, 959,
       741, 498, 195, 945,  17, 406, 331, 345, 846, 965, 403, 549, 457,
       486, 345, 237, 917, 263, 142, 430, 816, 281, 328, 347, 501, 939,
       241, 395, 961, 264, 597, 860, 669, 476, 252, 668, 860, 693, 938,
       698, 525, 644, 138, 635,  88, 573, 719, 552, 728, 145, 621, 663,
       321, 917, 941, 546, 833, 323,  95, 121, 589, 839, 842,  91, 580,
        95, 234, 686, 310, 110, 907, 593, 855, 392,  90, 146, 22

In [138]:
#While using np.histogram() function, we have to pass the array as well as specify the bin size

np.histogram(p, bins=[i for i in range(0,1000,250)])

#Interpretation:
#There are 22 numbers between 0 and 100
# So on
#There are 32 numbers between 800 and 900

(array([55, 59, 63]), array([  0, 250, 500, 750]))

In [140]:
#np.corrcoef
#The corrcoef is measures Pearson correlation, across columns/Features
#The corrcoef ranges from -1 to +1
#+1 denotes, Positive correlation, Like Corr between Exp and Salary, If One increases other also increases
#0 indicates no correlation and the features are independent
#-1 indicates, negative correlation. If the value of one feature increases then other decreases

salary = np.array([2000, 4000, 6000, 8000, 10000])
exp = np.array([0, 12, 4, 6, 18])

np.corrcoef(salary,exp)

array([[1.        , 0.67082039],
       [0.67082039, 1.        ]])

In [145]:
#np.isin
#np.isin is used to know whether multiple items are present in the array or not

items = [i for i in range(50)]

"""np.isin(p,items)"""
 #Generates a bool Mask, which can be overlapped with actual array to get the numbers
#Which are present

p[~(np.isin(p, items))] #Gives the elements which are not present in the items
p[(np.isin(p, items))]

array([31, 21, 19, 22, 22, 35, 34, 15, 29, 17, 45,  1])

In [148]:
#np.flip
#np.flip function reverses the order of the elements along the specified axis, preserving the shape of the array

print(salary)
print(np.flip(salary))

[ 2000  4000  6000  8000 10000]
[10000  8000  6000  4000  2000]


In [150]:
#np.flip can also be used for matrices
matrix = np.arange(15).reshape(5,3)
matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [154]:
np.flip(matrix) #1st row has been brough to last row and then elements are flipped(Column)
np.flip(matrix, axis=0) #Columns only are flipped
np.flip(matrix, axis=1) #Rows only are flipped

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9],
       [14, 13, 12]])

In [162]:
#np.put is used for editing the array
#Note:It permanently, replaces the elements of the array
test = np.arange(1,100,15)
test

array([ 1, 16, 31, 46, 61, 76, 91])

In [166]:
np.put(test,[0,1],[4,9]) #We are replacing elements at index position 0 and 1 with 4 and 9

"""Note: We must pass the indices, where we want to replace with the elements which we pass"""

#Syntax : np.put(array,[indices],[values])

'Note: We must pass the indices, where we want to replace with the elements which we pass'

In [167]:
test

array([ 4,  9, 31, 46, 61, 76, 91])

In [172]:
#np.delete, Deletes the element from the specified INDEX/INDICES

np.delete(test,[1,2])

array([ 4, 46, 61, 76, 91])

In [173]:
#np.clip,
"""Can be used in Gradient Clipping"""
#Keep only the values between specified range
np.clip(test,30,60)

array([30, 30, 31, 46, 60, 60, 60])