<a href="https://colab.research.google.com/github/saigowtham627/Fundementals/blob/main/PyTorch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What are tensors ?

**Tensors are like data structures**

**Tensors are specialized multidimensional array designed for mathematical and computational efficiency**

**Dimension can be defined as the number of directions in which tensors are spanning**

#Real World examples

**1. SCALARS : 0 dimensional tensors(A single number)**

*Scalars are not spreaded in any direction*

*Scalars represent a single value, often used for simple metrics or constants*

**Example**

*Loss value : After a forward pass, the loss function computes a loss value which is a scalar value, indicating the difference between Predicted and Target value*

*Ex: 5.0 or 3.14*

**2. Vectors : 1 dimensional tensors**

*Represents a sequence or collection of values*

**Example**

*Feature Vector : In NLP, each word in a sentance may be represented as a 1D vector using embeddings*

*Ex: [1.02, -3.14] a word embedding from a pre trained model like Glove Or Word2Vec*

**Matrices : 2 dimensional tensors**

*Represents a tabular or grid like data*

**Example**

*Grayscale Image : A gray scale image from MNIST dataset can be represented as a 2D tensor, where each entry corresponds to the Pixel intensity*

*Ex*: *[[0.5, 0.75]*

 *[0.90, 0.56]]*
      

**3D Tensors: Colour Images**

*Adds a third dimension, often used for stacking of data*

**Example**

*RGB Images : A single RGB images is represented as a 3D tnsor (width x height x channels)*

*Ex: RGB image of size 256x256: Shape : [256 256 3]*

**4D Tensors : Batches of RGB images**

*Adds the batch size as an additional dimension to 3D data*

**Example**

*Batches of RGB images : A dataset of colored images is represented as a 4D tensor*

*Ex: A batch of 32 color images, each of size 1024 x 1024 with 3 channels(RGB), would have a shape of [32, 1024, 1024, 3]*

**5D Tensors : Video Data**

*Adds a time dimension to the data, that changes over time (eg: Video frames)*

**Example**

*Video Clips: Represented as sequence of frames, where each frame is an RGB image*

**Ex: A batch of 10 video clips with 16 frames of size 64x64 and 3 channels(RGB), would have shape of [10, 16, 64, 64, 3]

#why are tensors useful ?

**Mathematical Operations**

*Tensors enable mathematical computations(Addition, Multiplication, Dot Product etc) necessary for neural network operations*

**Representation of Real World data**

*All the modalities like Image, Video, Audio can be represented as tensors*

*EX: Images represented as 3D tensors(Width x Height x channels)*

**Efficient computations**

*Tensors are optimized for hardware accelaration, allowing for performing computations on GPU and TPU, which are crucial for deep learning models*


#Where are tensors used in Deep Learning

**1. Data Storage**

*Training data like Images, text etc are stored in tensors*

**2. Weights and Biases**

*The learnable parameters of neural networks (Weights and Biases) are stored as tensors*

**3. Matrix Operations**

*Neural networks involve operations like matrix multiplications, dot products and broadcasting - All are perfomed using tensors*

**4. Training process**

*During forward pass tensors flow through the network*

*Gradients, represented as tensors, are calculated using backward pass**


#PyTorch comes pre installed on Google colab, no need to install it again..Just import it

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, using CPU")

GPU is not available, using CPU


##Creating tensors

In [ ]:
#Using empty
a = torch.empty(2,3) #Creates a 2x3 tensor with garbage values

In [ ]:
type(a) #Returns the type of variable

torch.Tensor

In [ ]:
#Using zeros
torch.zeros(2,3) #Creates a tensor of shape 2x3 initialized with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3) #Creates a tensor of shape 2x3 with all the values initialized with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3) #Creates a tensor of shape 2x3 in which all the values are initialized with random numbers between 0 and 1

#rand function does not have reproducibility
#But there occur some scenarios where we need reproducibility.
#So we can use seed in such scenarios

tensor([[0.5555, 0.7047, 0.0170],
        [0.8073, 0.3981, 0.1955]])

In [ ]:
#manual seed to produce same outputs every time
torch.manual_seed(143)

torch.rand(2,3) #Every time I run this code cell, I get the same output

tensor([[0.8653, 0.0099, 0.0284],
        [0.4898, 0.8311, 0.6590]])

In [ ]:
torch.manual_seed(143)

torch.rand(2,3) #Seed is same, so tensor created will also be the same

tensor([[0.8653, 0.0099, 0.0284],
        [0.4898, 0.8311, 0.6590]])

In [ ]:
#manual seed to produce same outputs every time
torch.manual_seed(99)

torch.rand(2,3) #The values are changed because the seed is changed from 143 to 99

tensor([[0.8961, 0.4005, 0.0814],
        [0.8735, 0.0440, 0.3929]])

In [ ]:
#We can create tensor with user specified values

torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

#Multiple lists in a single list

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#Other ways

#Arange
print("Using Arange:", torch.arange(0,10, 2)) #2 is the step size

#LinSpace
print("Usiing Linspace", torch.linspace(0, 10, 10)) #10 equally spaced values between 0 and 10

#Eye, Eye for Identity matrix
print("Using Eye", torch.eye(5))

#Using full, creating a tensor in which each item will be the specified number
print("Usig full", torch.full((3,3), 5)) #3x3 is the shape of the tensor, in which each number is 5

Using Arange: tensor([0, 2, 4, 6, 8])
Usiing Linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using Eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Usig full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes

In [ ]:
#Since Pytorch is based on Python, we can use its attributes like shape to find the shape of the tensor
x = torch.tensor([
  [12, 13, 14],
  [15, 16, 17],
  [18, 19, 20]
])

x

tensor([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]])

In [ ]:
x.shape

torch.Size([3, 3])

In [ ]:
#There will be some scenarios, where we want to create same tensor like the previously created one

torch.empty_like(x) #By passing x, we are specifying to copy the SHAPE OF X, BUT NOT X

tensor([[137044225748368,  94332618300240,  94330366722048],
        [            161, 137044225748336, 137044225748336],
        [ 94332595454992, 137040633846480,               1]])

In [ ]:
torch.zeros_like(x) #Create a tensor with zero values, the tensor should have shape of x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
#torch.rand_like(x)
#Will not work because, in tensor x all are integers.
#But rand function initializes tensor values with random float values
#So, we need to explicitly specify the type of numbers that rand should produce

torch.rand_like(x, dtype = torch.float32) #We have to explicitly specify the datatype of the numbers, we want to create

tensor([[0.5281, 0.7090, 0.4898],
        [0.9040, 0.6079, 0.2030],
        [0.4850, 0.3860, 0.2487]])

#Tensor Datatypes

In [ ]:
#Find data type

x.dtype #dtype is an attribute, it gives the datatype of the tensor


torch.int64

In [ ]:
#What if while creating a tensor, we have to specify the data type ?

torch.tensor([[
    [1,2,3],
    [4,5,6]
]], dtype = torch.int16)

tensor([[[1, 2, 3],
         [4, 5, 6]]], dtype=torch.int16)

In [ ]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#We can also, change the datatype of already created tensor
x.to(torch.float32)

tensor([[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.]])

#Mathematical Operations on Tensors

*1. Scalar Operation*

In [ ]:
b = torch.rand(4, 4)
b

tensor([[0.4202, 0.4106, 0.5983, 0.6427],
        [0.8562, 0.8896, 0.3385, 0.2666],
        [0.0758, 0.4729, 0.8209, 0.3007],
        [0.8803, 0.5988, 0.8614, 0.6859]])

In [ ]:
#Addition
b = b + 100
b

#Subtraction
b = b - 100
b

#Multiplication
b = b * b
b

#Division
b = b / 2
b

#Int division
b = b//2
b

#Mod
b = b % 2
b

#Power
b = b ** 2
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

*Between tensors*

In [ ]:
torch.manual_seed(14)
p = torch.rand(3,3)

torch.manual_seed(15)
q = torch.rand(3,3)

print(p)
print(q)

tensor([[0.5695, 0.0047, 0.9303],
        [0.7257, 0.8295, 0.7683],
        [0.0600, 0.1453, 0.2924]])
tensor([[0.2973, 0.2766, 0.7974],
        [0.3869, 0.9170, 0.4125],
        [0.5538, 0.5646, 0.5026]])


In [ ]:
#Adding p and q
p + q

#Subtracting p from q
q - p

#Multiply
p * q

#Division
p/q

#Int division
p // q

#Power
p ** q

#Mod
p % q

tensor([[0.2722, 0.0047, 0.1329],
        [0.3389, 0.8295, 0.3558],
        [0.0600, 0.1453, 0.2924]])

In [ ]:
c = torch.linspace(-10, 10, 10)
c

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])

In [ ]:
torch.abs(c) #Turn all the negative values into positive values

#To turn all the positive values into negative values

tensor([10.0000,  7.7778,  5.5556,  3.3333,  1.1111,  1.1111,  3.3333,  5.5556,
         7.7778, 10.0000])

In [ ]:
#Negative
#To turn all the positive values into negative values

torch.neg(c)

#Multiplies every value in the tensor with -ve

tensor([ 10.0000,   7.7778,   5.5556,   3.3333,   1.1111,  -1.1111,  -3.3333,
         -5.5556,  -7.7778, -10.0000])

In [ ]:
#Round
torch.round(c)

tensor([-10.,  -8.,  -6.,  -3.,  -1.,   1.,   3.,   6.,   8.,  10.])

In [ ]:
#Ceil
torch.ceil(c)

tensor([-10.,  -7.,  -5.,  -3.,  -1.,   2.,   4.,   6.,   8.,  10.])

In [ ]:
#Floor
torch.floor(c)

tensor([-10.,  -8.,  -6.,  -4.,  -2.,   1.,   3.,   5.,   7.,  10.])

In [ ]:
#clamp
"""By using clamp, we can put all the values in a specified range"""

torch.clamp(c, min = 2, max = 3) #All the values below 2 will be replced with 2 and all the values above 3, will be resplaced with 3


tensor([2., 2., 2., 2., 2., 2., 3., 3., 3., 3.])

#Reduction Operatiion

In [ ]:
torch.manual_seed(170)
e = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float16)
#Generates a tensor whose values lie 0 and 10

e

tensor([[2., 5., 0.],
        [6., 0., 2.]], dtype=torch.float16)

In [ ]:
#We can do all the mathematical operations at opnce on the whole tensor

torch.sum(e)

tensor(15)

In [ ]:
#Sum along columns
#Similar to numpy, row ---> 1 and coulmns ---> 0
torch.sum(e, dim = 0) #Column wise sum

tensor([8, 5, 2])

In [ ]:
#Sum along rows
#Similar to numpy, row ---> 1 and columns ---> 0
torch.sum(e, dim = 1)

tensor([7, 8])

In [ ]:
#Mean
torch.mean(e)

tensor(2.5000, dtype=torch.float16)

In [ ]:
#Mean along columns
torch.mean(e, dim = 0)

tensor([4.0000, 2.5000, 1.0000], dtype=torch.float16)

In [ ]:
#Mean along rows
torch.mean(e, dim = 1)

tensor([2.3340, 2.6660], dtype=torch.float16)

In [ ]:
#Median
torch.median(e)

tensor(2., dtype=torch.float16)

In [ ]:
#Median along rows
torch.median(e, dim = 1)

torch.return_types.median(
values=tensor([2., 2.], dtype=torch.float16),
indices=tensor([0, 2]))

In [ ]:
#Median along columns
torch.median(e, dim = 0)

torch.return_types.median(
values=tensor([2., 0., 0.], dtype=torch.float16),
indices=tensor([0, 1, 0]))

In [ ]:
#Max and Min
torch.max(e)

torch.min(e)

tensor(0., dtype=torch.float16)

In [ ]:
#Tensor Product
torch.prod(e)

tensor(0., dtype=torch.float16)

In [ ]:
#Torch Variance
torch.var(e)

tensor(6.3008, dtype=torch.float16)

In [ ]:
#Standard deviation
torch.std(e)

tensor(2.5098, dtype=torch.float16)

In [ ]:
#Argmax
torch.argmax(e) """Gives the POSITION of the maximum element, but not the max elemnent"""

tensor(3)

In [ ]:
#Argmin
torch.argmin(e) """Gives the position of the minimum element, but not the min element"""

tensor(2)

#Matrix Operations

In [ ]:
torch.manual_seed(1)
f = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float16)
g = torch.randint(size = (3, 2), low = 10, high = 20, dtype = torch.float16)

In [ ]:
print(f)
print(g)

tensor([[5., 9., 4.],
        [8., 3., 3.]], dtype=torch.float16)
tensor([[11., 11.],
        [19., 12.],
        [18., 19.]], dtype=torch.float16)


In [ ]:
#Matrix Multiplication
torch.matmul(f,g)

tensor([[298., 239.],
        [199., 181.]], dtype=torch.float16)

In [ ]:
#Dot product between vectors
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([4, 5])

#Dot product
torch.dot(vector1, vector2)

tensor(14)

In [ ]:
#Transpose
torch.transpose(f, dim0 = 0, dim1 = -1)

tensor([[5., 8.],
        [9., 3.],
        [4., 3.]], dtype=torch.float16)

In [ ]:
square = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float64)
square

tensor([[2., 7., 3.],
        [3., 3., 6.],
        [6., 6., 0.]], dtype=torch.float64)

In [ ]:
#Determinant of a tensor
torch.det(square) #When we are using Det or Inverse, we should have a matrix of atleast of float 64 precison, we SHOULDn't use lower precision

tensor(180., dtype=torch.float64)

In [ ]:
torch.inverse(square)

tensor([[-2.0000e-01,  1.0000e-01,  1.8333e-01],
        [ 2.0000e-01, -1.0000e-01, -1.6667e-02],
        [-5.0465e-19,  1.6667e-01, -8.3333e-02]], dtype=torch.float64)

#Comparision Operations

In [ ]:
torch.manual_seed(1999)
i = torch.randint(size = (5,5), low = 0, high = 100, dtype = torch.float64)
j = torch.randint(size = (5,5), low = 0, high = 10000, dtype = torch.float64)
print(i)
print(j)

tensor([[71., 32., 12., 24., 75.],
        [77., 47.,  6., 30., 19.],
        [ 6., 85., 70., 44., 36.],
        [ 4., 81., 64.,  0., 31.],
        [21., 32., 82., 94.,  7.]], dtype=torch.float64)
tensor([[5910., 4068., 6251., 6925., 9902.],
        [6837., 5661., 1946., 7978., 1912.],
        [5562., 4199., 1228., 9745., 4585.],
        [3031., 4354., 1372.,  891., 5841.],
        [2528., 7613., 3259., 4993., 7295.]], dtype=torch.float64)


In [ ]:
#Greater than
i > j

#Less than
i < j

#Equal to
i == j

#Not equal to
i != j

#Greater than equal to
i >= j

#Less than equal to
i <= j

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

#Special Operations

In [ ]:
torch.manual_seed(90)

s = torch.randint(size = (3,3), low = 10, high = 1000, dtype = torch.float64)

s

tensor([[809., 385., 730.],
        [ 61., 169., 759.],
        [454.,  18., 767.]], dtype=torch.float64)

In [ ]:
#Log
torch.log(s)

tensor([[6.6958, 5.9532, 6.5930],
        [4.1109, 5.1299, 6.6320],
        [6.1181, 2.8904, 6.6425]], dtype=torch.float64)

In [ ]:
#Exponenet(Exp)
torch.exp(s) #E Power every element

tensor([[        inf, 1.5973e+167,         inf],
        [ 3.1043e+26,  2.4875e+73,         inf],
        [1.4781e+197,  6.5660e+07,         inf]], dtype=torch.float64)

In [ ]:
#sqrt
torch.sqrt(s)

tensor([[28.4429, 19.6214, 27.0185],
        [ 7.8102, 13.0000, 27.5500],
        [21.3073,  4.2426, 27.6948]], dtype=torch.float64)

In [ ]:
#Sigmoid
torch.sigmoid(s) #Sigmoid of every element

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]], dtype=torch.float64)

In [ ]:
#Softmax, While applying softmax, we have to specify on which dimension we want to apply softmax
torch.softmax(s, dim = 0) #Softmax across columns

torch.softmax(s, dim = 1) #Softmax across rows

tensor([[ 1.0000e+00, 7.2300e-185,  4.9061e-35],
        [7.2854e-304, 5.8379e-257,  1.0000e+00],
        [1.1637e-136,  0.0000e+00,  1.0000e+00]], dtype=torch.float64)

In [ ]:
#ReLu
torch.relu(s)

tensor([[809., 385., 730.],
        [ 61., 169., 759.],
        [454.,  18., 767.]], dtype=torch.float64)

#Inplace Operations

#Inplace operations are used to reduce storage


In [2]:
torch.manual_seed(9000)
m = torch.randint(size = (3,3), low = 10, high = 1000, dtype = torch.float64)

n = torch.randint(size = (3,3), low = 10, high = 1000, dtype = torch.float64)

print(m)
print(n)

tensor([[752., 621.,  61.],
        [163., 833., 403.],
        [ 73., 242., 459.]], dtype=torch.float64)
tensor([[733., 395., 819.],
        [347., 190., 458.],
        [219.,  55., 397.]], dtype=torch.float64)


In [3]:
m.add_(n) #Adding n to m, equivalent to m = m + n

tensor([[1485., 1016.,  880.],
        [ 510., 1023.,  861.],
        [ 292.,  297.,  856.]], dtype=torch.float64)

In [5]:
m.relu_() #Relu on every element

tensor([[1485., 1016.,  880.],
        [ 510., 1023.,  861.],
        [ 292.,  297.,  856.]], dtype=torch.float64)

#_ represents, we are perfroming inplace operations

#Copying a tensor

In [12]:
c = torch.rand(size = (2,3))
c

tensor([[0.3116, 0.7261, 0.3698],
        [0.6494, 0.0225, 0.8767]])

In [14]:
#Easiest way to copy a tensor is using an assignment operator
d = c
d

tensor([[0.3116, 0.7261, 0.3698],
        [0.6494, 0.0225, 0.8767]])

In [16]:
#Now, say we are doing changes to c
c[1][2] = 0 #Making 2nd element in 1st row as 0
c

tensor([[0.3116, 0.7261, 0.3698],
        [0.6494, 0.0225, 0.0000]])

In [17]:
d#The [1][2] in d has also become 0, which is undesirable in some situations

tensor([[0.3116, 0.7261, 0.3698],
        [0.6494, 0.0225, 0.0000]])

In [19]:
d[0][0] = 1
d

tensor([[1.0000, 0.7261, 0.3698],
        [0.6494, 0.0225, 0.0000]])

In [20]:
c #We have changed 1st element of d, the same change has been applied to c, which is undesirable

tensor([[1.0000, 0.7261, 0.3698],
        [0.6494, 0.0225, 0.0000]])

*We are using passing by reference method, when using an assignment operator. We are creating a tensor in a memory location, we are giving the memory location to 2 different variables c and d here, so any variable can make changes in the address given to them*

In [21]:
id(c)

135057393864672

In [22]:
id(d) #Same as c

135057393864672

In [23]:
#To mitigate this problem we use CLONE function
p = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype = torch.float64)

p

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

In [25]:
q = p.clone()
q

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

In [27]:
p[0][0] = 100
p

tensor([[100.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]], dtype=torch.float64)

In [28]:
q # The 1st value of q has not been changed, even though we have changed in p

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float64)

In [29]:
id(p)

135060350878240

In [30]:
id(q) #The adress of p and q are different. It is similar to creating a new tensor at different location

135057187311024

#Tensors on GPU

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
print(torch.cuda.is_available()) #Checking whether the GPU is avaiable or not

True


In [3]:
#Setting GPU as the device to use
device = torch.device("cuda")

*Till now we have created the tensors on CPU, now we will be creating them on GPU/VRAM*

In [6]:
#Creating tensors on GPU
torch.randint(size=(2,3), low = 10, high = 100, device = device) #We have to specify device name, when using GPU

tensor([[32, 37, 96],
        [22, 60, 18]], device='cuda:0')

In [8]:
#2nd method is to move existing tensors which are on CPU to GPU
k = torch.randint(size = (2,3), low = 10, high = 100) #We are creating the tensor on CPU, as we have not specified the device
k

tensor([[81, 13, 54],
        [63, 98, 51]])

In [11]:
#Moving tensor "k" to GPU
i = k.to(device)

In [12]:
#Comparing cpu VS gpu
import time

size = 10000 #Ten Thousand

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

tik = time.time() #Start
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
tok = time.time() #End

print("Time taken by CPU :", tok-tik)

Time taken by CPU : 15.6508150100708


In [13]:
#Perfoming on GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

tik = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
tok = time.time()

print("Time taken by GPU:", tok - tik)

Time taken by GPU: 0.11988449096679688


In [14]:
print("Speed up achevied by GPU:", 15.6508150100708 / 0.11988449096679688)

Speed up achevied by GPU: 130.54912177427053


#Reshaping tensors

In [19]:
h = torch.ones(4,4)
h

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
h.reshape(2,2,2,2) #2 blocks, each consisting 2 tensors, each tensor is of size 2x2

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

#Rele for reshaping: Product of original dimensions should be equal to product of reshaped.
*Here original size is 4x4, product is 16,
reshaped is 2x2x2x2, product is 16....Matched !!*

In [21]:
#flatten
torch.flatten(h)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
j = torch.randint(size = (2,3,4), low = 10, high = 100, dtype = torch.float32)
j

tensor([[[28., 81., 97., 38.],
         [73., 98., 74., 23.],
         [43., 24., 34., 10.]],

        [[82., 74., 65., 57.],
         [70., 71., 19., 85.],
         [93., 22., 19., 93.]]])

In [27]:
torch.permute(j, dims=(2,1,0)).shape

#(2,3,4) shape became (4,3,2) shape

torch.Size([4, 3, 2])

In [35]:
#Squeze and Unsqueeze
#Unsqueeze adds an extra dimension
c = torch.rand(226,226,3) #Typical dimension of an image while using a CNN

torch.unsqueeze(c, 1).shape #Adds an extra dimension at Position 1
torch.unsqueeze(c, 0).shape #Adds an extra dimension at position 0..We have to specify the position
torch.unsqueeze(c, 2).shape #Adds an extra dimension at position 2
torch.unsqueeze(c, 3).shape #Adds an extra dimension at position 3

#Unsqueeze is useful we want to perform batch processing

torch.Size([226, 226, 3, 1])

In [41]:
#Squeeze
#When we want to squeeze the tensor into lower dimensions, we use Squueze function
c = torch.squeeze(c).shape

In [51]:
x = torch.rand(1,20)
x

tensor([[0.5673, 0.3689, 0.0748, 0.8244, 0.9635, 0.4867, 0.7644, 0.9947, 0.1281,
         0.8149, 0.8489, 0.5453, 0.4170, 0.9597, 0.4995, 0.7887, 0.0743, 0.5815,
         0.5637, 0.3016]])

In [53]:
torch.squeeze(x).shape

torch.Size([20])

#NumPy and PyTorch

In [54]:
import numpy as np

In [56]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [57]:
#Our task is to convert the tensor into NumPy array
b = a.numpy()

In [58]:
type(b)

numpy.ndarray

In [59]:
c = np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [60]:
torch.from_numpy(c)

tensor([1, 2, 3, 4, 5])

*numpy() and from_numpy() are 2 functions to convert tensor into numpy array and numpy array into tensor respectively*